[package]
name = "jwt-d-e-rust"
version = "0.0.0"
authors = ["Leo <leo@leopolanco.com>"]
edition = "2021"

[dependencies]
rocket = "0.4.10"
rocket_codegen = "0.4.10"
rocket_cors = "0.5.2"

[dependencies.rocket_contrib]
version = "0.4.10"
default-features = false
features = ["json"]